// frontend/src/lib/mfa.ts

/**
 * MFA Manager (Frontend Utility)
 * 
 * SECURITY NOTES:
 * - TOTP Secret Generation and Verification are handled ENTIRELY by the backend.
 * - This file ONLY handles formatting data for display.
 * - ⚠️ WARNING: The 'generateBackupCodes' function below is for UI placeholders ONLY.
 *   REAL backup codes are generated by the backend (mfa-setup-verify) using crypto.randomBytes.
 *   DO NOT use codes generated here for authentication.
 */

export class MFAManager {
  /**
   * Formats a backend-provided secret into a standard OTPAuth URI for QR code generation.
   * 
   * @param secret - The base32 secret string returned from the backend (mfa-setup-init)
   * @param email - The user's email address (used as the account label)
   * @param issuer - The name of your application
   * @returns A valid otpauth:// URL compatible with Google Authenticator, Authy, etc.
   */
  static formatQRUrl(secret: string, email: string, issuer: string = "SecureWebProduct"): string {
    // 1. Validate Inputs to prevent injection
    if (!secret || typeof secret !== 'string') {
      throw new Error('Invalid secret provided');
    }
    
    // Whitelist validation for email and issuer (allow only safe chars)
    const safeEmail = email.replace(/[^a-zA-Z0-9@.+-]/g, '');
    const safeIssuer = issuer.replace(/[^a-zA-Z0-9\s-]/g, '');

    if (!safeEmail) {
      throw new Error('Invalid email format');
    }

    // Encode the email to handle special characters safely in the URI
    const label = encodeURIComponent(safeEmail);
    const encodedIssuer = encodeURIComponent(safeIssuer);
    
    // Ensure secret is alphanumeric/base32 safe (basic check)
    const safeSecret = secret.replace(/[^A-Z2-7=]/gi, ''); // Base32 charset
    
    if (!safeSecret) {
      throw new Error('Invalid secret format');
    }

    return `otpauth://totp/${encodedIssuer}:${label}?secret=${safeSecret}&issuer=${encodedIssuer}&algorithm=SHA1&digits=6&period=30`;
  }

  /**
   * ⚠️ DEPRECATED / PLACEHOLDER ONLY
   * 
   * Generates a list of random alphanumeric strings for UI demonstration or user notes.
   * 
   * SECURITY WARNING:
   * - These codes are generated client-side using Web Crypto API for better randomness,
   *   but they are NOT the actual backup codes used for authentication.
   * - The ACTUAL backup codes are generated by the BACKEND (mfa-setup-verify) and sent to the user.
   * - DO NOT use these codes for login. They are for display purposes only.
   * 
   * @param count - Number of codes to generate
   * @param length - Length of each code
   * @returns Array of random strings (NOT valid auth codes)
   */
  static generatePlaceholderCodes(count: number = 10, length: number = 12): string[] {
    const codes: string[] = [];
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    
    // Use Web Crypto API for better randomness (though still not for auth)
    const array = new Uint32Array(length * count);
    window.crypto.getRandomValues(array);

    let arrayIndex = 0;
    for (let i = 0; i < count; i++) {
      let code = '';
      for (let j = 0; j < length; j++) {
        const randomIndex = array[arrayIndex++] % chars.length;
        code += chars[randomIndex];
      }
      codes.push(code);
    }
    
    return codes;
  }

  /**
   * Validates the format of a backup code entered by the user.
   * Does NOT verify against the database (backend does that).
   * 
   * @param code - The code entered by the user
   * @returns true if format is valid (alphanumeric, correct length)
   */
  static isValidFormat(code: string): boolean {
    // Allow 12 alphanumeric characters (case insensitive)
    return /^[A-Z0-9]{12}$/i.test(code);
  }
}
